# Copyright 2015, Perceivon Hosting Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY PERCEIVON HOSTING INC. AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL PERCEIVON HOSTING INC. OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---
# generic postgres user
- name: Check if creating {{ postgresql_data.user }} user is necessary
  iocage: state=exec tag={{ postgresql_jail.uuid }} user=pgsql cmd="/bin/sh -c \"echo SELECT rolname FROM pg_roles WHERE rolname = \\\'{{ postgresql_data.user }}\\\' | psql template1 | grep {{ postgresql_data.user }}\" "

  register: postgresql_user_present
  ignore_errors: true
  tags:
  - db
  - pgsql
  - pgsql-roles

- name: Create PostgreSQL user
  iocage: state=exec tag={{ postgresql_jail.uuid }} user=pgsql cmd="/bin/sh -c \"echo CREATE ROLE {{ postgresql_data.user }} WITH SUPERUSER LOGIN CREATEDB CREATEROLE ENCRYPTED PASSWORD \\\'{{ postgresql_data.password }}\\\' | psql template1 \" "
  when:
  - postgresql_user_present | failed
  tags:
  - db
  - pgsql
  - pgsql-roles

# redmine user
- name: Check if creating {{ redmine_data.user }} user is necessary
  iocage: state=exec tag={{ postgresql_jail.uuid }} user=pgsql cmd="/bin/sh -c \"echo SELECT rolname FROM pg_roles WHERE rolname = \\\'{{ redmine_data.user }}\\\' | psql template1 | grep {{ redmine_data.user }}\" "
  register: redmine_user_present
  ignore_errors: true
  tags:
  - db
  - pgsql
  - pgsql-roles

- name: Create Redmine user
  iocage: state=exec tag={{ postgresql_jail.uuid }} user=pgsql cmd="/bin/sh -c \"echo CREATE ROLE {{ redmine_data.user }} WITH LOGIN ENCRYPTED PASSWORD \\\'{{ redmine_data.password }}\\\' | psql template1 \" "
  when:
  - redmine_user_present | failed
  tags:
  - db
  - pgsql
  - pgsql-roles

# zabbix user
- name: Check if creating {{ zabbix_data.user }} user is necessary
  iocage: state=exec tag={{ postgresql_jail.uuid }} user=pgsql cmd="/bin/sh -c \"echo SELECT rolname FROM pg_roles WHERE rolname = \\\'{{ zabbix_data.user }}\\\' | psql template1 | grep {{ zabbix_data.user }}\" "
  register: zabbix_user_present
  ignore_errors: true
  tags:
  - db
  - pgsql
  - pgsql-roles

- name: Create zabbix user
  iocage: state=exec tag={{ postgresql_jail.uuid }} user=pgsql cmd="/bin/sh -c \"echo CREATE ROLE {{ zabbix_data.user }} WITH LOGIN ENCRYPTED PASSWORD \\\'{{ zabbix_data.password }}\\\' | psql template1 \" "
  when:
  - zabbix_user_present | failed
  tags:
  - db
  - pgsql
  - pgsql-roles
