# Copyright 2015, Perceivon Hosting Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY PERCEIVON HOSTING INC. AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL PERCEIVON HOSTING INC. OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---
- name: Check if zpool is configured for iocage
  shell: /sbin/zpool get -H -o value comment {{ iocage_zpool }}
  changed_when: true
  register: zpool_comment
  always_run: true
  tags:
  - iocage-comb
  notify: check if iocage release was fetched

- name: Mark zpool for iocage usage
  command: /sbin/zpool set comment=iocage {{ iocage_zpool }}
  when: zpool_comment.stdout.find("^-$") > 0
  tags:
  - iocage-comb

#- name: Install iocage
#  tags: iocage-devel
#  pkgng:
#    name: iocage
#    state: present

- name: Check if we can skip downloading the release
  stat: path='{{ iocage_releases_dir }}/{{ iocage_release_version }}'
  register: release_dir
  tags:
  - iocage-comb

- name: Fetch FreeBSD release {{ iocage_release_version }}
  shell: echo "{{ iocage_release_version }}" | /usr/local/sbin/iocage fetch ftpfiles="base.txz src.txz"
  when: release_dir.stat.isdir is undefined
  tags:
  - iocage-comb

- name: Check if it is now present
  stat: path='{{ iocage_releases_dir }}/{{ iocage_release_version }}'
  when: release_dir.stat.isdir is undefined
  tags:
    - iocage-comb
  register: release_dir

# FIXME: broken
#- assert:
#    that:
#     - release_dir.stat.exists
#     - release_dir.stat.isdir
#  tags:
#    - iocage
#    - iocage-debug

- name: Check if basejail already exists
  iocage: state=exists tag='basejail_{{ iocage_release_version }}'
  register: basejail
  tags:
  - iocage-comb

- name: Create FreeBSD {{ iocage_release_version }} basejail
  iocage: state=basejail tag=basejail_{{ iocage_release_version }} release={{ iocage_release_version }}
  when:
  - "'uuid' in basejail and (basejail['uuid'] is not defined or basejail['uuid'] == '-')" 
  tags:
  - iocage-comb
  notify: check if iocage release was fetched

- name: Create pkglist file
  tags:
  - iocage-comb
  copy:
    src: pkglist.txt
    dest: '{{ iocage_jails_dir }}/pkglist.txt'

- name: Enable iocage service
  tags:
  - iocage-comb
  service:
    name: iocage
    enabled: true
