---
- name: Find UUID for {{ jail_name }}
  shell: /usr/local/sbin/iocage show ip4_addr | grep {{ jail_ip }} | cut -d ' ' -f 1
  changed_when: false
  register: jail_uuid

- name: Create jail {{ jail_name }}
  command: /usr/local/sbin/iocage create tag={{ jail_name }} ip4_addr={{ jail_ip_addr }} boot=on pkglist={{ iocage_jails_dir }}/pkglist.txt
  when: not jail_uuid.stdout

- name: Find UUID for {{ jail_name }}
  shell: /usr/local/sbin/iocage show ip4_addr | grep {{ jail_ip }} | cut -d ' ' -f 1
  changed_when: false
  register: jail_uuid

- name: Register jail's home diretory
  command: echo {{ iocage_jails_dir }}/{{ jail_uuid.stdout }}/root
  changed_when: false
  register: jail_home

