---
- name: Create ansible user on {{ jail_name }}
  lineinfile:
    dest: '{{ jail_home.stdout }}/etc/master.passwd'
    state: present
    insertafter: EOF
    line: 'vagrant:*:1001:1001::0:0:Ansible Management User:/home/vagrant:/bin/sh'
  register: user

- name: Update user database
  command: pwd_mkdb -p -d {{ jail_home.stdout }}/etc {{ jail_home.stdout }}/etc/master.passwd
  when: user.changed

- name: Create directories to sudoers file
  file:
    path: '{{ jail_home.stdout }}/usr/local/etc/sudoers.d'
    state: directory

- name: Add sudo rules for ansible user on {{ jail_name }}
  copy:
    src: sudoers.ansible
    dest: '{{ jail_home.stdout }}/usr/local/etc/sudoers.d/ansible'
    validate: 'visudo -cf %s'
