---
- name: Copy pf.conf
  template:
    src: 'pf.conf.j2'
    dest: '/etc/pf.conf'
    mode: 0640

- name: Check nat_jails defintion file
  stat: path=/etc/pf.table.nat_jails
  register: table_file

- name: Ensure nat_jails definition file exists
  file: path=/etc/pf.table.nat_jails
        state=touch
        mode=640
  when: not table_file.stat.exists

- name: Enable pf firewall
  service: name=pf
           enabled=true

- name: Enable pf log
  service: name=pflog
           enabled=true
